---
stephs:
  com.github.blamevic.steph.irc.IRCSteph:
    hostname: anarchy.esper.net
    port: 6667
    username: StephanieDola
    realname: Stephanie Dola
    debug: true

processors:
  com.github.blamevic.steph.processors.HelloProcessor:
